export const PHONE_FETCH_REQUEST = 'PHONE_FETCH_REQUEST';
export const PHONE_FETCH_SUCCESS = 'PHONE_FETCH_SUCCESS';
export const PHONE_FETCH_ERROR = 'PHONE_FETCH_ERROR';

export const FEEDBACK_FETCH_REQUEST = 'FEEDBACK_FETCH_REQUEST';
export const FEEDBACK_FETCH_SUCCESS = 'FEEDBACK_FETCH_SUCCESS';
export const FEEDBACK_FETCH_ERROR = 'FEEDBACK_FETCH_ERROR';
