export const ADD_COMPARE = 'ADD_TO_COMPARE';
export const DELETE_COMPARE = 'DELETE_COMPARE';
export const CLEAR_COMPARE = 'CLEAR_COMPARE';
export const COMPARE_UPDATE_LOCAL_STORAGE = 'COMPARE_UPDATE_LOCAL_STORAGE';

