export const PROJECT_SINGLE_FETCH_REQUEST = "PROJECT_SINGLE_FETCH_REQUEST";
export const PROJECT_SINGLE_FETCH_SUCCESS = "PROJECT_SINGLE_FETCH_SUCCESS";
export const PROJECT_SINGLE_FETCH_ERROR = "PROJECT_SINGLE_FETCH_ERROR";